/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PoolGetResult : TBase
{
  private APIResponse _status;
  private Pool _pool;
  private List<Transaction> _transactions;

  public APIResponse Status
  {
    get
    {
      return _status;
    }
    set
    {
      __isset.status = true;
      this._status = value;
    }
  }

  public Pool Pool
  {
    get
    {
      return _pool;
    }
    set
    {
      __isset.pool = true;
      this._pool = value;
    }
  }

  public List<Transaction> Transactions
  {
    get
    {
      return _transactions;
    }
    set
    {
      __isset.transactions = true;
      this._transactions = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool status;
    public bool pool;
    public bool transactions;
  }

  public PoolGetResult() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Status = new APIResponse();
              Status.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Pool = new Pool();
              Pool.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Transactions = new List<Transaction>();
                TList _list13 = iprot.ReadListBegin();
                for( int _i14 = 0; _i14 < _list13.Count; ++_i14)
                {
                  Transaction _elem15;
                  _elem15 = new Transaction();
                  _elem15.Read(iprot);
                  Transactions.Add(_elem15);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("PoolGetResult");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Status != null && __isset.status) {
        field.Name = "status";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Status.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Pool != null && __isset.pool) {
        field.Name = "pool";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Pool.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Transactions != null && __isset.transactions) {
        field.Name = "transactions";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Transactions.Count));
          foreach (Transaction _iter16 in Transactions)
          {
            _iter16.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("PoolGetResult(");
    bool __first = true;
    if (Status != null && __isset.status) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Status: ");
      __sb.Append(Status== null ? "<null>" : Status.ToString());
    }
    if (Pool != null && __isset.pool) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Pool: ");
      __sb.Append(Pool== null ? "<null>" : Pool.ToString());
    }
    if (Transactions != null && __isset.transactions) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Transactions: ");
      __sb.Append(Transactions);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

